// @flow

export const LOAD_SCANNER: "RNAPP/LOAD_SCANNER" = "RNAPP/LOAD_SCANNER";
export const LOAD_SCAN_PENDING = "RNAPP/LOAD_SCAN_PENDING";
export const LOAD_SCAN_SUCCESS = "RNAPP/LOAD_SCAN_SUCCESS";
export const LOAD_SCAN_FAILURE = "RNAPP/LOAD_SCAN_FAILURE";
