// @flow

export const LOAD_SCANNER: "RNAPP/LOAD_SCANNER" = "RNAPP/LOAD_SCANNER";
export const LOAD_SCAN_PENDING = "RNAPP/LOAD_SCAN_PENDING";
export const LOAD_SCAN_SUCCESS = "RNAPP/LOAD_SCAN_SUCCESS";
export const LOAD_SCAN_FAILURE = "RNAPP/LOAD_SCAN_FAILURE";
export const PROCESS_SCAN_DATA = "RNAPP/PROCESS_SCAN_DATA";
export const RESET_SCAN_DATA = "RNAPP/RESET_SCAN_DATA";
export const SEARCH_NUMBER = "RNAPP/SEARCH_NUMBER";
export const NAVIGATE_PROFILE = "RNAPP/NAVIGATE_PROFILE";
