// flow-typed signature: 9529811b078b069470eb774491cac041
// flow-typed version: <<STUB>>/expo_v^31.0.2/flow_v0.92.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'expo'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'expo' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'expo/AppEntry' {
  declare module.exports: any;
}

declare module 'expo/bin/cli' {
  declare module.exports: any;
}

declare module 'expo/build/__mocks__/Constants-development' {
  declare module.exports: any;
}

declare module 'expo/build/__tests__/Amplitude-test' {
  declare module.exports: any;
}

declare module 'expo/build/__tests__/AuthSession-test' {
  declare module.exports: any;
}

declare module 'expo/build/__tests__/Constants-test' {
  declare module.exports: any;
}

declare module 'expo/build/__tests__/ErrorRecovery-test' {
  declare module.exports: any;
}

declare module 'expo/build/__tests__/Expo-test' {
  declare module.exports: any;
}

declare module 'expo/build/__tests__/Facebook-test' {
  declare module.exports: any;
}

declare module 'expo/build/__tests__/Font-test' {
  declare module.exports: any;
}

declare module 'expo/build/__tests__/Location-test' {
  declare module.exports: any;
}

declare module 'expo/build/__tests__/Notifications-test' {
  declare module.exports: any;
}

declare module 'expo/build/__tests__/SecureStore-test' {
  declare module.exports: any;
}

declare module 'expo/build/__tests__/Segment-test' {
  declare module.exports: any;
}

declare module 'expo/build/__tests__/WebBrowser-test' {
  declare module.exports: any;
}

declare module 'expo/build/Amplitude' {
  declare module.exports: any;
}

declare module 'expo/build/apisAreAvailable' {
  declare module.exports: any;
}

declare module 'expo/build/AR' {
  declare module.exports: any;
}

declare module 'expo/build/AuthSession' {
  declare module.exports: any;
}

declare module 'expo/build/av/Audio' {
  declare module.exports: any;
}

declare module 'expo/build/av/Audio/AudioAvailability' {
  declare module.exports: any;
}

declare module 'expo/build/av/Audio/Recording' {
  declare module.exports: any;
}

declare module 'expo/build/av/Audio/Sound' {
  declare module.exports: any;
}

declare module 'expo/build/av/AV' {
  declare module.exports: any;
}

declare module 'expo/build/av/Video' {
  declare module.exports: any;
}

declare module 'expo/build/Branch' {
  declare module.exports: any;
}

declare module 'expo/build/Brightness' {
  declare module.exports: any;
}

declare module 'expo/build/Calendar' {
  declare module.exports: any;
}

declare module 'expo/build/DangerZone' {
  declare module.exports: any;
}

declare module 'expo/build/DocumentPicker' {
  declare module.exports: any;
}

declare module 'expo/build/effects/BlurView.android' {
  declare module.exports: any;
}

declare module 'expo/build/effects/BlurView.ios' {
  declare module.exports: any;
}

declare module 'expo/build/effects/LinearGradient' {
  declare module.exports: any;
}

declare module 'expo/build/effects/NativeLinearGradient.android' {
  declare module.exports: any;
}

declare module 'expo/build/effects/NativeLinearGradient.ios' {
  declare module.exports: any;
}

declare module 'expo/build/environment/__tests__/validate-test' {
  declare module.exports: any;
}

declare module 'expo/build/environment/logging' {
  declare module.exports: any;
}

declare module 'expo/build/environment/validate' {
  declare module.exports: any;
}

declare module 'expo/build/ErrorRecovery' {
  declare module.exports: any;
}

declare module 'expo/build/Expo' {
  declare module.exports: any;
}

declare module 'expo/build/facebook-ads/AdIconView' {
  declare module.exports: any;
}

declare module 'expo/build/facebook-ads/AdMediaView' {
  declare module.exports: any;
}

declare module 'expo/build/facebook-ads/AdSettings' {
  declare module.exports: any;
}

declare module 'expo/build/facebook-ads/AdTriggerView' {
  declare module.exports: any;
}

declare module 'expo/build/facebook-ads/BannerAd' {
  declare module.exports: any;
}

declare module 'expo/build/facebook-ads/index' {
  declare module.exports: any;
}

declare module 'expo/build/facebook-ads/InterstitialAdManager' {
  declare module.exports: any;
}

declare module 'expo/build/facebook-ads/NativeAdsManager' {
  declare module.exports: any;
}

declare module 'expo/build/facebook-ads/withNativeAd' {
  declare module.exports: any;
}

declare module 'expo/build/Facebook' {
  declare module.exports: any;
}

declare module 'expo/build/Fingerprint' {
  declare module.exports: any;
}

declare module 'expo/build/GestureHandler' {
  declare module.exports: any;
}

declare module 'expo/build/Google' {
  declare module.exports: any;
}

declare module 'expo/build/Haptic' {
  declare module.exports: any;
}

declare module 'expo/build/Icon' {
  declare module.exports: any;
}

declare module 'expo/build/ImageManipulator' {
  declare module.exports: any;
}

declare module 'expo/build/ImagePicker' {
  declare module.exports: any;
}

declare module 'expo/build/IntentLauncherAndroid' {
  declare module.exports: any;
}

declare module 'expo/build/KeepAwake' {
  declare module.exports: any;
}

declare module 'expo/build/launch/AppLoading' {
  declare module.exports: any;
}

declare module 'expo/build/launch/AppLoadingNativeWrapper' {
  declare module.exports: any;
}

declare module 'expo/build/launch/registerRootComponent' {
  declare module.exports: any;
}

declare module 'expo/build/launch/RootErrorBoundary' {
  declare module.exports: any;
}

declare module 'expo/build/launch/SplashScreen' {
  declare module.exports: any;
}

declare module 'expo/build/Linking' {
  declare module.exports: any;
}

declare module 'expo/build/Localization' {
  declare module.exports: any;
}

declare module 'expo/build/logs/__tests__/Logs-test' {
  declare module.exports: any;
}

declare module 'expo/build/logs/__tests__/LogSerialization-test' {
  declare module.exports: any;
}

declare module 'expo/build/logs/__tests__/RemoteConsole-test' {
  declare module.exports: any;
}

declare module 'expo/build/logs/__tests__/RemoteLogging-test' {
  declare module.exports: any;
}

declare module 'expo/build/logs/__tests__/RemoteLogs-test' {
  declare module.exports: any;
}

declare module 'expo/build/logs/Logs' {
  declare module.exports: any;
}

declare module 'expo/build/logs/LogSerialization' {
  declare module.exports: any;
}

declare module 'expo/build/logs/RemoteConsole' {
  declare module.exports: any;
}

declare module 'expo/build/logs/RemoteLogging' {
  declare module.exports: any;
}

declare module 'expo/build/MailComposer' {
  declare module.exports: any;
}

declare module 'expo/build/Notifications' {
  declare module.exports: any;
}

declare module 'expo/build/Payments' {
  declare module.exports: any;
}

declare module 'expo/build/Pedometer' {
  declare module.exports: any;
}

declare module 'expo/build/ScreenOrientation' {
  declare module.exports: any;
}

declare module 'expo/build/SecureStore' {
  declare module.exports: any;
}

declare module 'expo/build/Speech' {
  declare module.exports: any;
}

declare module 'expo/build/SQLite' {
  declare module.exports: any;
}

declare module 'expo/build/StoreReview' {
  declare module.exports: any;
}

declare module 'expo/build/Svg' {
  declare module.exports: any;
}

declare module 'expo/build/takeSnapshotAsync' {
  declare module.exports: any;
}

declare module 'expo/build/timer/polyfillNextTick' {
  declare module.exports: any;
}

declare module 'expo/build/Updates' {
  declare module.exports: any;
}

declare module 'expo/build/Util' {
  declare module.exports: any;
}

declare module 'expo/build/WebBrowser' {
  declare module.exports: any;
}

declare module 'expo/tools/hashAssetFiles' {
  declare module.exports: any;
}

declare module 'expo/tools/LogReporter' {
  declare module.exports: any;
}

// Filename aliases
declare module 'expo/AppEntry.js' {
  declare module.exports: $Exports<'expo/AppEntry'>;
}
declare module 'expo/bin/cli.js' {
  declare module.exports: $Exports<'expo/bin/cli'>;
}
declare module 'expo/build/__mocks__/Constants-development.js' {
  declare module.exports: $Exports<'expo/build/__mocks__/Constants-development'>;
}
declare module 'expo/build/__tests__/Amplitude-test.js' {
  declare module.exports: $Exports<'expo/build/__tests__/Amplitude-test'>;
}
declare module 'expo/build/__tests__/AuthSession-test.js' {
  declare module.exports: $Exports<'expo/build/__tests__/AuthSession-test'>;
}
declare module 'expo/build/__tests__/Constants-test.js' {
  declare module.exports: $Exports<'expo/build/__tests__/Constants-test'>;
}
declare module 'expo/build/__tests__/ErrorRecovery-test.js' {
  declare module.exports: $Exports<'expo/build/__tests__/ErrorRecovery-test'>;
}
declare module 'expo/build/__tests__/Expo-test.js' {
  declare module.exports: $Exports<'expo/build/__tests__/Expo-test'>;
}
declare module 'expo/build/__tests__/Facebook-test.js' {
  declare module.exports: $Exports<'expo/build/__tests__/Facebook-test'>;
}
declare module 'expo/build/__tests__/Font-test.js' {
  declare module.exports: $Exports<'expo/build/__tests__/Font-test'>;
}
declare module 'expo/build/__tests__/Location-test.js' {
  declare module.exports: $Exports<'expo/build/__tests__/Location-test'>;
}
declare module 'expo/build/__tests__/Notifications-test.js' {
  declare module.exports: $Exports<'expo/build/__tests__/Notifications-test'>;
}
declare module 'expo/build/__tests__/SecureStore-test.js' {
  declare module.exports: $Exports<'expo/build/__tests__/SecureStore-test'>;
}
declare module 'expo/build/__tests__/Segment-test.js' {
  declare module.exports: $Exports<'expo/build/__tests__/Segment-test'>;
}
declare module 'expo/build/__tests__/WebBrowser-test.js' {
  declare module.exports: $Exports<'expo/build/__tests__/WebBrowser-test'>;
}
declare module 'expo/build/Amplitude.js' {
  declare module.exports: $Exports<'expo/build/Amplitude'>;
}
declare module 'expo/build/apisAreAvailable.js' {
  declare module.exports: $Exports<'expo/build/apisAreAvailable'>;
}
declare module 'expo/build/AR.js' {
  declare module.exports: $Exports<'expo/build/AR'>;
}
declare module 'expo/build/AuthSession.js' {
  declare module.exports: $Exports<'expo/build/AuthSession'>;
}
declare module 'expo/build/av/Audio.js' {
  declare module.exports: $Exports<'expo/build/av/Audio'>;
}
declare module 'expo/build/av/Audio/AudioAvailability.js' {
  declare module.exports: $Exports<'expo/build/av/Audio/AudioAvailability'>;
}
declare module 'expo/build/av/Audio/Recording.js' {
  declare module.exports: $Exports<'expo/build/av/Audio/Recording'>;
}
declare module 'expo/build/av/Audio/Sound.js' {
  declare module.exports: $Exports<'expo/build/av/Audio/Sound'>;
}
declare module 'expo/build/av/AV.js' {
  declare module.exports: $Exports<'expo/build/av/AV'>;
}
declare module 'expo/build/av/Video.js' {
  declare module.exports: $Exports<'expo/build/av/Video'>;
}
declare module 'expo/build/Branch.js' {
  declare module.exports: $Exports<'expo/build/Branch'>;
}
declare module 'expo/build/Brightness.js' {
  declare module.exports: $Exports<'expo/build/Brightness'>;
}
declare module 'expo/build/Calendar.js' {
  declare module.exports: $Exports<'expo/build/Calendar'>;
}
declare module 'expo/build/DangerZone.js' {
  declare module.exports: $Exports<'expo/build/DangerZone'>;
}
declare module 'expo/build/DocumentPicker.js' {
  declare module.exports: $Exports<'expo/build/DocumentPicker'>;
}
declare module 'expo/build/effects/BlurView.android.js' {
  declare module.exports: $Exports<'expo/build/effects/BlurView.android'>;
}
declare module 'expo/build/effects/BlurView.ios.js' {
  declare module.exports: $Exports<'expo/build/effects/BlurView.ios'>;
}
declare module 'expo/build/effects/LinearGradient.js' {
  declare module.exports: $Exports<'expo/build/effects/LinearGradient'>;
}
declare module 'expo/build/effects/NativeLinearGradient.android.js' {
  declare module.exports: $Exports<'expo/build/effects/NativeLinearGradient.android'>;
}
declare module 'expo/build/effects/NativeLinearGradient.ios.js' {
  declare module.exports: $Exports<'expo/build/effects/NativeLinearGradient.ios'>;
}
declare module 'expo/build/environment/__tests__/validate-test.js' {
  declare module.exports: $Exports<'expo/build/environment/__tests__/validate-test'>;
}
declare module 'expo/build/environment/logging.js' {
  declare module.exports: $Exports<'expo/build/environment/logging'>;
}
declare module 'expo/build/environment/validate.js' {
  declare module.exports: $Exports<'expo/build/environment/validate'>;
}
declare module 'expo/build/ErrorRecovery.js' {
  declare module.exports: $Exports<'expo/build/ErrorRecovery'>;
}
declare module 'expo/build/Expo.js' {
  declare module.exports: $Exports<'expo/build/Expo'>;
}
declare module 'expo/build/facebook-ads/AdIconView.js' {
  declare module.exports: $Exports<'expo/build/facebook-ads/AdIconView'>;
}
declare module 'expo/build/facebook-ads/AdMediaView.js' {
  declare module.exports: $Exports<'expo/build/facebook-ads/AdMediaView'>;
}
declare module 'expo/build/facebook-ads/AdSettings.js' {
  declare module.exports: $Exports<'expo/build/facebook-ads/AdSettings'>;
}
declare module 'expo/build/facebook-ads/AdTriggerView.js' {
  declare module.exports: $Exports<'expo/build/facebook-ads/AdTriggerView'>;
}
declare module 'expo/build/facebook-ads/BannerAd.js' {
  declare module.exports: $Exports<'expo/build/facebook-ads/BannerAd'>;
}
declare module 'expo/build/facebook-ads/index.js' {
  declare module.exports: $Exports<'expo/build/facebook-ads/index'>;
}
declare module 'expo/build/facebook-ads/InterstitialAdManager.js' {
  declare module.exports: $Exports<'expo/build/facebook-ads/InterstitialAdManager'>;
}
declare module 'expo/build/facebook-ads/NativeAdsManager.js' {
  declare module.exports: $Exports<'expo/build/facebook-ads/NativeAdsManager'>;
}
declare module 'expo/build/facebook-ads/withNativeAd.js' {
  declare module.exports: $Exports<'expo/build/facebook-ads/withNativeAd'>;
}
declare module 'expo/build/Facebook.js' {
  declare module.exports: $Exports<'expo/build/Facebook'>;
}
declare module 'expo/build/Fingerprint.js' {
  declare module.exports: $Exports<'expo/build/Fingerprint'>;
}
declare module 'expo/build/GestureHandler.js' {
  declare module.exports: $Exports<'expo/build/GestureHandler'>;
}
declare module 'expo/build/Google.js' {
  declare module.exports: $Exports<'expo/build/Google'>;
}
declare module 'expo/build/Haptic.js' {
  declare module.exports: $Exports<'expo/build/Haptic'>;
}
declare module 'expo/build/Icon.js' {
  declare module.exports: $Exports<'expo/build/Icon'>;
}
declare module 'expo/build/ImageManipulator.js' {
  declare module.exports: $Exports<'expo/build/ImageManipulator'>;
}
declare module 'expo/build/ImagePicker.js' {
  declare module.exports: $Exports<'expo/build/ImagePicker'>;
}
declare module 'expo/build/IntentLauncherAndroid.js' {
  declare module.exports: $Exports<'expo/build/IntentLauncherAndroid'>;
}
declare module 'expo/build/KeepAwake.js' {
  declare module.exports: $Exports<'expo/build/KeepAwake'>;
}
declare module 'expo/build/launch/AppLoading.js' {
  declare module.exports: $Exports<'expo/build/launch/AppLoading'>;
}
declare module 'expo/build/launch/AppLoadingNativeWrapper.js' {
  declare module.exports: $Exports<'expo/build/launch/AppLoadingNativeWrapper'>;
}
declare module 'expo/build/launch/registerRootComponent.js' {
  declare module.exports: $Exports<'expo/build/launch/registerRootComponent'>;
}
declare module 'expo/build/launch/RootErrorBoundary.js' {
  declare module.exports: $Exports<'expo/build/launch/RootErrorBoundary'>;
}
declare module 'expo/build/launch/SplashScreen.js' {
  declare module.exports: $Exports<'expo/build/launch/SplashScreen'>;
}
declare module 'expo/build/Linking.js' {
  declare module.exports: $Exports<'expo/build/Linking'>;
}
declare module 'expo/build/Localization.js' {
  declare module.exports: $Exports<'expo/build/Localization'>;
}
declare module 'expo/build/logs/__tests__/Logs-test.js' {
  declare module.exports: $Exports<'expo/build/logs/__tests__/Logs-test'>;
}
declare module 'expo/build/logs/__tests__/LogSerialization-test.js' {
  declare module.exports: $Exports<'expo/build/logs/__tests__/LogSerialization-test'>;
}
declare module 'expo/build/logs/__tests__/RemoteConsole-test.js' {
  declare module.exports: $Exports<'expo/build/logs/__tests__/RemoteConsole-test'>;
}
declare module 'expo/build/logs/__tests__/RemoteLogging-test.js' {
  declare module.exports: $Exports<'expo/build/logs/__tests__/RemoteLogging-test'>;
}
declare module 'expo/build/logs/__tests__/RemoteLogs-test.js' {
  declare module.exports: $Exports<'expo/build/logs/__tests__/RemoteLogs-test'>;
}
declare module 'expo/build/logs/Logs.js' {
  declare module.exports: $Exports<'expo/build/logs/Logs'>;
}
declare module 'expo/build/logs/LogSerialization.js' {
  declare module.exports: $Exports<'expo/build/logs/LogSerialization'>;
}
declare module 'expo/build/logs/RemoteConsole.js' {
  declare module.exports: $Exports<'expo/build/logs/RemoteConsole'>;
}
declare module 'expo/build/logs/RemoteLogging.js' {
  declare module.exports: $Exports<'expo/build/logs/RemoteLogging'>;
}
declare module 'expo/build/MailComposer.js' {
  declare module.exports: $Exports<'expo/build/MailComposer'>;
}
declare module 'expo/build/Notifications.js' {
  declare module.exports: $Exports<'expo/build/Notifications'>;
}
declare module 'expo/build/Payments.js' {
  declare module.exports: $Exports<'expo/build/Payments'>;
}
declare module 'expo/build/Pedometer.js' {
  declare module.exports: $Exports<'expo/build/Pedometer'>;
}
declare module 'expo/build/ScreenOrientation.js' {
  declare module.exports: $Exports<'expo/build/ScreenOrientation'>;
}
declare module 'expo/build/SecureStore.js' {
  declare module.exports: $Exports<'expo/build/SecureStore'>;
}
declare module 'expo/build/Speech.js' {
  declare module.exports: $Exports<'expo/build/Speech'>;
}
declare module 'expo/build/SQLite.js' {
  declare module.exports: $Exports<'expo/build/SQLite'>;
}
declare module 'expo/build/StoreReview.js' {
  declare module.exports: $Exports<'expo/build/StoreReview'>;
}
declare module 'expo/build/Svg.js' {
  declare module.exports: $Exports<'expo/build/Svg'>;
}
declare module 'expo/build/takeSnapshotAsync.js' {
  declare module.exports: $Exports<'expo/build/takeSnapshotAsync'>;
}
declare module 'expo/build/timer/polyfillNextTick.js' {
  declare module.exports: $Exports<'expo/build/timer/polyfillNextTick'>;
}
declare module 'expo/build/Updates.js' {
  declare module.exports: $Exports<'expo/build/Updates'>;
}
declare module 'expo/build/Util.js' {
  declare module.exports: $Exports<'expo/build/Util'>;
}
declare module 'expo/build/WebBrowser.js' {
  declare module.exports: $Exports<'expo/build/WebBrowser'>;
}
declare module 'expo/tools/hashAssetFiles.js' {
  declare module.exports: $Exports<'expo/tools/hashAssetFiles'>;
}
declare module 'expo/tools/LogReporter.js' {
  declare module.exports: $Exports<'expo/tools/LogReporter'>;
}
