// flow-typed signature: 25389b963e994c56f80c49d37d697b22
// flow-typed version: <<STUB>>/react-native-json-tree_v^1.2.0/flow_v0.92.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-json-tree'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-json-tree' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-json-tree/src/createStylingFromTheme' {
  declare module.exports: any;
}

declare module 'react-native-json-tree/src/getCollectionEntries' {
  declare module.exports: any;
}

declare module 'react-native-json-tree/src/index' {
  declare module.exports: any;
}

declare module 'react-native-json-tree/src/ItemRange' {
  declare module.exports: any;
}

declare module 'react-native-json-tree/src/JSONArrayNode' {
  declare module.exports: any;
}

declare module 'react-native-json-tree/src/JSONArrow' {
  declare module.exports: any;
}

declare module 'react-native-json-tree/src/JSONIterableNode' {
  declare module.exports: any;
}

declare module 'react-native-json-tree/src/JSONNestedNode' {
  declare module.exports: any;
}

declare module 'react-native-json-tree/src/JSONNode' {
  declare module.exports: any;
}

declare module 'react-native-json-tree/src/JSONObjectNode' {
  declare module.exports: any;
}

declare module 'react-native-json-tree/src/JSONValueNode' {
  declare module.exports: any;
}

declare module 'react-native-json-tree/src/objType' {
  declare module.exports: any;
}

declare module 'react-native-json-tree/src/themes/solarized' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-json-tree/src/createStylingFromTheme.js' {
  declare module.exports: $Exports<'react-native-json-tree/src/createStylingFromTheme'>;
}
declare module 'react-native-json-tree/src/getCollectionEntries.js' {
  declare module.exports: $Exports<'react-native-json-tree/src/getCollectionEntries'>;
}
declare module 'react-native-json-tree/src/index.js' {
  declare module.exports: $Exports<'react-native-json-tree/src/index'>;
}
declare module 'react-native-json-tree/src/ItemRange.js' {
  declare module.exports: $Exports<'react-native-json-tree/src/ItemRange'>;
}
declare module 'react-native-json-tree/src/JSONArrayNode.js' {
  declare module.exports: $Exports<'react-native-json-tree/src/JSONArrayNode'>;
}
declare module 'react-native-json-tree/src/JSONArrow.js' {
  declare module.exports: $Exports<'react-native-json-tree/src/JSONArrow'>;
}
declare module 'react-native-json-tree/src/JSONIterableNode.js' {
  declare module.exports: $Exports<'react-native-json-tree/src/JSONIterableNode'>;
}
declare module 'react-native-json-tree/src/JSONNestedNode.js' {
  declare module.exports: $Exports<'react-native-json-tree/src/JSONNestedNode'>;
}
declare module 'react-native-json-tree/src/JSONNode.js' {
  declare module.exports: $Exports<'react-native-json-tree/src/JSONNode'>;
}
declare module 'react-native-json-tree/src/JSONObjectNode.js' {
  declare module.exports: $Exports<'react-native-json-tree/src/JSONObjectNode'>;
}
declare module 'react-native-json-tree/src/JSONValueNode.js' {
  declare module.exports: $Exports<'react-native-json-tree/src/JSONValueNode'>;
}
declare module 'react-native-json-tree/src/objType.js' {
  declare module.exports: $Exports<'react-native-json-tree/src/objType'>;
}
declare module 'react-native-json-tree/src/themes/solarized.js' {
  declare module.exports: $Exports<'react-native-json-tree/src/themes/solarized'>;
}
