// @flow

export const PROCEED_ACTION = "RNAPP/PROCEED_ACTION";
export const PROCEED_ACTION_FAILURE = "RNAPP/PROCEED_ACTION_FAILURE";
export const SELECT_PROFILE = "RNAPP/SELECT_PROFILE";
export const RESET_PROFILE_DATA = "RNAPP/RESET_PROFILE_DATA";
