export const AUTHENTICATE = "RNAPP/AUTHENTICATE";
export const INVALIDATE = "RNAPP/INVALIDATE";
export const AUTH_PENDING = "RNAPP/AUTH_PENDING";
export const AUTH_SUCCESS = "RNAPP/AUTH_SUCCESS";
export const AUTH_FAILURE = "RNAPP/AUTH_FAILURE";
export const RESET_AUTH = "RNAPP/RESET_AUTH";
export const RESET_ERROR = "RNAPP/RESET_ERROR";
