export const FACE_ID_AUTHENTICATE = "RNAPP/FACE_ID_AUTHENTICATE";
export const AUTHENTICATE = "RNAPP/AUTHENTICATE";
export const RESETALLDATA = "RNAPP/RESETALLDATA";
export const AUTH_PENDING = "RNAPP/AUTH_PENDING";
export const AUTH_SUCCESS = "RNAPP/AUTH_SUCCESS";
export const AUTH_FAILURE = "RNAPP/AUTH_FAILURE";
export const RESET_AUTH = "RNAPP/RESET_AUTH";
export const RESET_ERROR = "RNAPP/RESET_ERROR";
