# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

update_fastlane

default_platform(:android)

platform :android do

    before_all do
     sh "rm -rf ../app/build"
     sh "cp ./../../dev/fastlane/key.keystore ./../app/key.keystore"
    end

    after_all do
      sh "rm -f ./../app/key.keystore"
      sh "rm -f ./api.json"
      sh "rm -f ./app/google-services.json"
      sh "rm -f ./../app/src/debug/google-services.json"
      sh "rm -f ./../app/src/release/google-services.json"
    end

  lane :playstore do
   increment_version_code(gradle_file_path: "app/build.gradle")

    gradle(
      task: 'bundle',
      build_type: 'Release'
    )

    # Uploads the APK built in the gradle step above and releases it to all production users
    upload_to_play_store(
        track: 'alpha',
        rollout: '0.51'
      )

      gradle(
        task: "clean"
      )
  end
end
